package com.itofficerhub.entity;

public enum Topic {
	NETWORKING,
	DBMS,
	OPERATING_SYSTEMS,
	SECURITY,
	WEB_TECHNOLOGIES,
	DATA_STRUCTURES,
	COMPUTER_ORGANIZATION,
	SOFTWARE_ENGINEERING,
	CLOUD_COMPUTING,
	DIGITAL_ELECTRONICS,
	/** TCS NQT / campus aptitude */
	QUANTITATIVE_APTITUDE,
	LOGICAL_REASONING,
	VERBAL_ABILITY
}
